services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/backend/src
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    environment:
      - VITE_API_URL=http://backend:3000
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/frontend/src
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
