FROM node:24-alpine

RUN corepack enable

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN yarn install

COPY backend/ ./backend/

EXPOSE 3000
CMD ["yarn", "workspace", "backend", "start:dev"]